import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#101415",
        primary: "#c3f5ff",
        "inverse-primary": "#006875",
        outline: "#849396",
        "surface-container-lowest": "#0b0f10",
        "on-error": "#690005",
        "on-surface": "#e0e3e5",
        "on-background": "#e0e3e5",
        "inverse-surface": "#e0e3e5",
        "surface-container": "#1d2022",
        "outline-variant": "#3b494c",
        "surface-tint": "#00daf3",
        "surface-container-high": "#272a2c",
        "secondary-fixed-dim": "#ffb68e",
        "on-tertiary-container": "#6834d1",
        "surface-variant": "#323537",
        "on-tertiary-fixed": "#23005c",
        surface: "#101415",
        tertiary: "#f2e9ff",
        "on-primary-fixed": "#001f24",
        secondary: "#ffb68e",
        "secondary-container": "#ea6b00",
        "surface-container-low": "#191c1e",
        "on-secondary-fixed": "#331200",
        "on-tertiary": "#3c0091",
        "inverse-on-surface": "#2d3133",
        "on-primary": "#00363d",
        "on-secondary-container": "#491d00",
        "primary-fixed": "#9cf0ff",
        "primary-container": "#00e5ff",
        "tertiary-container": "#d9c8ff",
        "tertiary-fixed-dim": "#d0bcff",
        "surface-container-highest": "#323537",
        "on-primary-fixed-variant": "#004f58",
        "error-container": "#93000a",
        "secondary-fixed": "#ffdbca",
        "on-surface-variant": "#bac9cc",
        "primary-fixed-dim": "#00daf3",
        "on-tertiary-fixed-variant": "#5516be",
        "tertiary-fixed": "#e9ddff",
        "on-error-container": "#ffdad6",
        "on-secondary": "#532200",
        background: "#101415",
        "on-secondary-fixed-variant": "#763300",
        "surface-bright": "#363a3b",
        "on-primary-container": "#00626e",
        error: "#ffb4ab",
        "ai-accent": "#8B5CF6",
        "obs-void": "#03060A",
        "obs-deep": "#060B12",
        "obs-surface": "#0B1320",
        "obs-elevated": "#101B2E",
        "obs-border": "#1B2A40",
        "starlight": "#F8FAFC",
        "stellar-cyan": "#38BDF8",
        "ice-blue": "#7DD3FC",
        "controlled-violet": "#8B5CF6",
        "transit-amber": "#F59E0B",
        // Modern DSO / Linear-style tokens
        "surface-void": "#030508",
        "surface-base": "#090a0f",
        "surface-panel": "#0e111a",
        "surface-raised": "#141824",
        "surface-overlay": "#1a2030",
        "border-subtle": "rgba(255, 255, 255, 0.08)",
        "border-medium": "rgba(255, 255, 255, 0.15)",
        "border-prominent": "rgba(56, 189, 248, 0.28)",
        "candidate-emerald": "#10B981",
        "muted-slate": "#64748B",
        "secondary-slate": "#94A3B8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.375rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "panel-padding": "20px",
        gutter: "16px",
        unit: "4px",
        "max-width": "1600px",
        margin: "32px",
      },
      fontFamily: {
        display: ["var(--font-display)", "sans-serif"],
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
        "label-caps": ["var(--font-mono)", "monospace"],
        "headline-lg": ["var(--font-display)", "sans-serif"],
        "data-mono": ["var(--font-mono)", "monospace"],
        "hero-lg": ["var(--font-display)", "sans-serif"],
        "body-md": ["var(--font-sans)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-display)", "sans-serif"],
        "headline-md": ["var(--font-display)", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.12em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "hero-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
