import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#101415",
        primary: "#c3f5ff",
        "inverse-primary": "#006875",
        outline: "#849396",
        "surface-container-lowest": "#0b0f10",
        "on-error": "#690005",
        "on-surface": "#e0e3e5",
        "on-background": "#e0e3e5",
        "inverse-surface": "#e0e3e5",
        "surface-container": "#1d2022",
        "outline-variant": "#3b494c",
        "surface-tint": "#00daf3",
        "surface-container-high": "#272a2c",
        "secondary-fixed-dim": "#ffb68e",
        "on-tertiary-container": "#6834d1",
        "surface-variant": "#323537",
        "on-tertiary-fixed": "#23005c",
        surface: "#101415",
        tertiary: "#f2e9ff",
        "on-primary-fixed": "#001f24",
        secondary: "#ffb68e",
        "secondary-container": "#ea6b00",
        "surface-container-low": "#191c1e",
        "on-secondary-fixed": "#331200",
        "on-tertiary": "#3c0091",
        "inverse-on-surface": "#2d3133",
        "on-primary": "#00363d",
        "on-secondary-container": "#491d00",
        "primary-fixed": "#9cf0ff",
        "primary-container": "#00e5ff",
        "tertiary-container": "#d9c8ff",
        "tertiary-fixed-dim": "#d0bcff",
        "surface-container-highest": "#323537",
        "on-primary-fixed-variant": "#004f58",
        "error-container": "#93000a",
        "secondary-fixed": "#ffdbca",
        "on-surface-variant": "#bac9cc",
        "primary-fixed-dim": "#00daf3",
        "on-tertiary-fixed-variant": "#5516be",
        "tertiary-fixed": "#e9ddff",
        "on-error-container": "#ffdad6",
        "on-secondary": "#532200",
        background: "#101415",
        "on-secondary-fixed-variant": "#763300",
        "surface-bright": "#363a3b",
        "on-primary-container": "#00626e",
        error: "#ffb4ab",
        "ai-accent": "#8B5CF6",
        // Editorial Observatory Palette
        paper: "#F7F5EF",
        "paper-subtle": "#F1EEE5",
        "paper-warm": "#FAF9F5",
        "paper-contrast": "#E8E4D8",
        "obs-dark": "#090D0F",
        "obs-sidebar": "#090D0F",
        "obs-surface": "#0D1215",
        "obs-panel": "#12181C",
        "obs-border": "rgba(255, 255, 255, 0.08)",
        "paper-border": "rgba(15, 23, 42, 0.08)",
        "paper-border-medium": "rgba(15, 23, 42, 0.14)",
        ink: "#0F172A",
        "ink-muted": "#475569",
        "ink-faint": "#94A3B8",
        signal: "#1D4ED8",
        "signal-light": "#3B82F6",
        "signal-subtle": "rgba(29, 78, 216, 0.08)",
        // Status colors
        "status-candidate": "#059669",
        "status-non-detection": "#D97706",
        "status-failed": "#DC2626",
        "status-processing": "#2563EB",
        // Legacy / compatibility tokens
        "obs-void": "#07090D",
        "obs-deep": "#090D0F",
        "obs-elevated": "#12181C",
        starlight: "#F8FAFC",
        "stellar-cyan": "#2563EB",
        "ice-blue": "#3B82F6",
        "transit-amber": "#D97706",
        "candidate-emerald": "#059669",
        "muted-slate": "#64748B",
        "secondary-slate": "#94A3B8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.375rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "panel-padding": "20px",
        gutter: "16px",
        unit: "4px",
        "max-width": "1600px",
        margin: "32px",
      },
      fontFamily: {
        serif: ["var(--font-serif)", "Georgia", "serif"],
        display: ["var(--font-serif)", "Georgia", "serif"],
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      fontSize: {
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.12em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "hero-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
