import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#101415",
        primary: "#c3f5ff",
        "inverse-primary": "#006875",
        outline: "#849396",
        "surface-container-lowest": "#0b0f10",
        "on-error": "#690005",
        "on-surface": "#e0e3e5",
        "on-background": "#e0e3e5",
        "inverse-surface": "#e0e3e5",
        "surface-container": "#1d2022",
        "outline-variant": "#3b494c",
        "surface-tint": "#00daf3",
        "surface-container-high": "#272a2c",
        "secondary-fixed-dim": "#ffb68e",
        "on-tertiary-container": "#6834d1",
        "surface-variant": "#323537",
        "on-tertiary-fixed": "#23005c",
        surface: "#101415",
        tertiary: "#f2e9ff",
        "on-primary-fixed": "#001f24",
        secondary: "#ffb68e",
        "secondary-container": "#ea6b00",
        "surface-container-low": "#191c1e",
        "on-secondary-fixed": "#331200",
        "on-tertiary": "#3c0091",
        "inverse-on-surface": "#2d3133",
        "on-primary": "#00363d",
        "on-secondary-container": "#491d00",
        "primary-fixed": "#9cf0ff",
        "primary-container": "#00e5ff",
        "tertiary-container": "#d9c8ff",
        "tertiary-fixed-dim": "#d0bcff",
        "surface-container-highest": "#323537",
        "on-primary-fixed-variant": "#004f58",
        "error-container": "#93000a",
        "secondary-fixed": "#ffdbca",
        "on-surface-variant": "#bac9cc",
        "primary-fixed-dim": "#00daf3",
        "on-tertiary-fixed-variant": "#5516be",
        "tertiary-fixed": "#e9ddff",
        "on-error-container": "#ffdad6",
        "on-secondary": "#532200",
        background: "#101415",
        "on-secondary-fixed-variant": "#763300",
        "surface-bright": "#363a3b",
        "on-primary-container": "#00626e",
        error: "#ffb4ab",
        "ai-accent": "#8B5CF6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "panel-padding": "20px",
        gutter: "16px",
        unit: "4px",
        "max-width": "1600px",
        margin: "32px",
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "hero-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "hero-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
